#ifndef SRC_DEFINITIONS_H_
#define SRC_DEFINITIONS_H_


// gamepad stuff
#define GAMEPAD_2_INPUT_CHANNEL		1
#define GAMEPAD_1_INPUT_CHANNEL		0

#define GAMEPAD_1_STICK_X			0
#define GAMEPAD_1_STICK_Y			1

#define GAMEPAD_2_STICK_X			0
#define GAMEPAD_2_STICK_Y			1

//motor channels
#define WINCH_OUTPUT_CHANNEL		0
#define LEFT_DRIVE_OUTPUT_CHANNEL	0
#define RIGHT_DRIVE_OUTPUT_CHANNEL	1

#define LEFT_ENCODER_CHANNEL_A		0
#define LEFT_ENCODER_CHANNEL_B		1

#define RIGHT_ENCODER_CHANNEL_A		2
#define RIGHT_ENCODER_CHANNEL_B		3





#endif /* DEBUG_SRC_DEFINITIONS_H_ */
