#ifndef SRC_DEFINITIONS_H_
#define SRC_DEFINITIONS_H_


// gamepad stuff
#define GAMEPAD_2_INPUT_CHANNEL		1
#define GAMEPAD_1_INPUT_CHANNEL		0

#define GAMEPAD_1_STICK_X			0
#define GAMEPAD_1_STICK_Y			1

#define GAMEPAD_2_STICK_X			0
#define GAMEPAD_2_STICK_Y			1

//motor channels
#define WINCH_OUTPUT_CHANNEL		0
#define LEFT_DRIVE_OUTPUT_CHANNEL	1
#define RIGHT_DRIVE_OUTPUT_CHANNEL	2
#define CONVEYOR_OUTPUT_CHANNEL		3

#define LEFT_ENCODER_CHANNEL_A		0
#define LEFT_ENCODER_CHANNEL_B		1

#define RIGHT_ENCODER_CHANNEL_A		2
#define RIGHT_ENCODER_CHANNEL_B		3
//other
#define ENCODER_VALUES_PER_INCH		56.7
#define ROBOT_WIDTH					23





#endif /* DEBUG_SRC_DEFINITIONS_H_ */
